### ISSUE TITLE
Is TPM Device needed for verifier?

### ISSUE THREAD

**Issue by choehojun** [salrashid123/go_tpm_remote_attestation#2]
According to main function of grpc_verifier.go, tpm device is needed for verifier to use OpenTPM library function. Is there any other way to run this code without real tpm device in remote environment?

**Comment by salrashid123** [comment]
no, you do't technically need a TPM on the verifier.  I have it there because the default makecredential method [here](https://github.com/salrashid123/go_tpm_remote_attestation/blob/push/src/grpc_verifier.go#L495) in the legacy api seems to have it as a parameter use of it:

https://github.com/google/go-tpm/blob/main/legacy/tpm2/tpm2.go#L1096

(i havn't tried setting it to null or using the simulator on the verifier)


eg, with [tpm2_makecredential](https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_makecredential.1.md) you can just as easily set ` --tcti=none` (no tpm needed)

```bash
echo "12345678" | tpm2 makecredential -Q -u ek.pem -s - -n $loaded_key_name --tcti=none  -o mkcred.out -G rsa
```

a todo is to not use the legacy api  and maybe instead some higher abstraction: eg [go-attestation](https://github.com/google/go-attestation)

ref: 

https://github.com/salrashid123/tls_ak
